/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.spadesscorekeeper;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jarodh
 */
public class SpadesScoreKeeperUI extends javax.swing.JFrame {

    private float team1Nello;
    private float team2Nello;
    /**
     * Creates new form SpadesScoreKeeperUI
     */
    public SpadesScoreKeeperUI() {
        initComponents();
        setLocationRelativeTo(null);
        jTextFieldTeam1Score.setText("0");
        jTextFieldTeam2Score.setText("0");
        team1Nello = 0;
        team2Nello = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTeam1Results = new javax.swing.ButtonGroup();
        buttonGroupTeam2Results = new javax.swing.ButtonGroup();
        jPanelTeam1 = new javax.swing.JPanel();
        jPanelTeam1Bid = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTeam1Player1Bid = new javax.swing.JTextField();
        jTextFieldTeam1Player2Bid = new javax.swing.JTextField();
        jPanelTeam1Actual = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTeam1Total = new javax.swing.JTextField();
        jRadioButtonTeam1NelloSucceeded = new javax.swing.JRadioButton();
        jRadioButtonTeam1NelloFailed = new javax.swing.JRadioButton();
        jRadioButtonTeam1BlindSucceeded = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTeam1Score = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelTeam2 = new javax.swing.JPanel();
        jPanelTeam2Bid = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTeam2Player1Bid = new javax.swing.JTextField();
        jTextFieldTeam2Player2Bid = new javax.swing.JTextField();
        jPanelTeam2Actual = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTeam2Total = new javax.swing.JTextField();
        jRadioButtonTeam2NelloSucceeded = new javax.swing.JRadioButton();
        jRadioButtonTeam2NelloFailed = new javax.swing.JRadioButton();
        jRadioButtonTeam2BlindSucceeded = new javax.swing.JRadioButton();
        jRadioButtonTeam2BlindFailed = new javax.swing.JRadioButton();
        jRadioButtonTeam2ResultsNone = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTeam2Score = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButtonCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(736, 450));

        jPanelTeam1.setBorder(javax.swing.BorderFactory.createTitledBorder("Team 1"));
        jPanelTeam1.setPreferredSize(new java.awt.Dimension(353, 340));

        jPanelTeam1Bid.setBorder(javax.swing.BorderFactory.createTitledBorder("Bid"));

        jLabel3.setText("Player 1 Bid:");

        jLabel4.setText("Player 2 Bid:");

        javax.swing.GroupLayout jPanelTeam1BidLayout = new javax.swing.GroupLayout(jPanelTeam1Bid);
        jPanelTeam1Bid.setLayout(jPanelTeam1BidLayout);
        jPanelTeam1BidLayout.setHorizontalGroup(
            jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam1BidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTeam1Player1Bid)
                    .addComponent(jTextFieldTeam1Player2Bid))
                .addContainerGap())
        );
        jPanelTeam1BidLayout.setVerticalGroup(
            jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam1BidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTeam1Player1Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam1BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTeam1Player2Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTeam1Actual.setBorder(javax.swing.BorderFactory.createTitledBorder("Actual"));

        jLabel5.setText("Total Tricks Taken:");

        buttonGroupTeam1Results.add(jRadioButtonTeam1NelloSucceeded);
        jRadioButtonTeam1NelloSucceeded.setText("Nello Succeeded");
        jRadioButtonTeam1NelloSucceeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeam1NelloSucceededActionPerformed(evt);
            }
        });

        buttonGroupTeam1Results.add(jRadioButtonTeam1NelloFailed);
        jRadioButtonTeam1NelloFailed.setText("Nello Failed");
        jRadioButtonTeam1NelloFailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeam1NelloFailedActionPerformed(evt);
            }
        });

        buttonGroupTeam1Results.add(jRadioButtonTeam1BlindSucceeded);
        jRadioButtonTeam1BlindSucceeded.setText("Blind Nello Succeeded");
        jRadioButtonTeam1BlindSucceeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTeam1BlindSucceededActionPerformed(evt);
            }
        });

        buttonGroupTeam1Results.add(jRadioButton4);
        jRadioButton4.setText("Blind Nello Failed");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroupTeam1Results.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("None");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTeam1ActualLayout = new javax.swing.GroupLayout(jPanelTeam1Actual);
        jPanelTeam1Actual.setLayout(jPanelTeam1ActualLayout);
        jPanelTeam1ActualLayout.setHorizontalGroup(
            jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam1ActualLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTeam1Total)
                .addContainerGap())
            .addGroup(jPanelTeam1ActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTeam1BlindSucceeded)
                    .addComponent(jRadioButtonTeam1NelloSucceeded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButtonTeam1NelloFailed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeam1ActualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton5)
                .addGap(129, 129, 129))
        );
        jPanelTeam1ActualLayout.setVerticalGroup(
            jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam1ActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTeam1Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTeam1NelloSucceeded)
                    .addComponent(jRadioButtonTeam1NelloFailed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam1ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTeam1BlindSucceeded)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Score:");

        jTextFieldTeam1Score.setEditable(false);
        jTextFieldTeam1Score.setFocusable(false);

        jButton1.setText("Log Score");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTeam1Layout = new javax.swing.GroupLayout(jPanelTeam1);
        jPanelTeam1.setLayout(jPanelTeam1Layout);
        jPanelTeam1Layout.setHorizontalGroup(
            jPanelTeam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTeam1Bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTeam1Actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTeam1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTeam1Score)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeam1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanelTeam1Layout.setVerticalGroup(
            jPanelTeam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam1Layout.createSequentialGroup()
                .addGroup(jPanelTeam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTeam1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeam1Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeam1Actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanelTeam2.setBorder(javax.swing.BorderFactory.createTitledBorder("Team 2"));
        jPanelTeam2.setPreferredSize(new java.awt.Dimension(353, 370));

        jPanelTeam2Bid.setBorder(javax.swing.BorderFactory.createTitledBorder("Bid"));

        jLabel6.setText("Player 1 Bid:");

        jLabel7.setText("Player 2 Bid:");

        javax.swing.GroupLayout jPanelTeam2BidLayout = new javax.swing.GroupLayout(jPanelTeam2Bid);
        jPanelTeam2Bid.setLayout(jPanelTeam2BidLayout);
        jPanelTeam2BidLayout.setHorizontalGroup(
            jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2BidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTeam2Player1Bid)
                    .addComponent(jTextFieldTeam2Player2Bid))
                .addContainerGap())
        );
        jPanelTeam2BidLayout.setVerticalGroup(
            jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2BidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTeam2Player1Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam2BidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTeam2Player2Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTeam2Actual.setBorder(javax.swing.BorderFactory.createTitledBorder("Actual"));

        jLabel8.setText("Total Tricks Taken:");

        buttonGroupTeam2Results.add(jRadioButtonTeam2NelloSucceeded);
        jRadioButtonTeam2NelloSucceeded.setText("Nello Succeeded");

        buttonGroupTeam2Results.add(jRadioButtonTeam2NelloFailed);
        jRadioButtonTeam2NelloFailed.setText("Nello Failed");

        buttonGroupTeam2Results.add(jRadioButtonTeam2BlindSucceeded);
        jRadioButtonTeam2BlindSucceeded.setText("Blind Nello Succeeded");

        buttonGroupTeam2Results.add(jRadioButtonTeam2BlindFailed);
        jRadioButtonTeam2BlindFailed.setText("Blind Nello Failed");

        buttonGroupTeam2Results.add(jRadioButtonTeam2ResultsNone);
        jRadioButtonTeam2ResultsNone.setSelected(true);
        jRadioButtonTeam2ResultsNone.setText("None");

        javax.swing.GroupLayout jPanelTeam2ActualLayout = new javax.swing.GroupLayout(jPanelTeam2Actual);
        jPanelTeam2Actual.setLayout(jPanelTeam2ActualLayout);
        jPanelTeam2ActualLayout.setHorizontalGroup(
            jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2ActualLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTeam2Total)
                .addContainerGap())
            .addGroup(jPanelTeam2ActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTeam2BlindSucceeded)
                    .addComponent(jRadioButtonTeam2NelloSucceeded))
                .addGap(6, 6, 6)
                .addGroup(jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTeam2NelloFailed)
                    .addComponent(jRadioButtonTeam2BlindFailed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeam2ActualLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonTeam2ResultsNone)
                .addGap(129, 129, 129))
        );
        jPanelTeam2ActualLayout.setVerticalGroup(
            jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2ActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldTeam2Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTeam2NelloSucceeded)
                    .addComponent(jRadioButtonTeam2NelloFailed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTeam2ActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTeam2BlindSucceeded)
                    .addComponent(jRadioButtonTeam2BlindFailed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jRadioButtonTeam2ResultsNone))
        );

        jLabel2.setText("Score:");

        jTextFieldTeam2Score.setEditable(false);
        jTextFieldTeam2Score.setFocusable(false);

        jButton2.setText("Log Score");

        javax.swing.GroupLayout jPanelTeam2Layout = new javax.swing.GroupLayout(jPanelTeam2);
        jPanelTeam2.setLayout(jPanelTeam2Layout);
        jPanelTeam2Layout.setHorizontalGroup(
            jPanelTeam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2Layout.createSequentialGroup()
                .addGroup(jPanelTeam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTeam2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTeam2Score))
                    .addGroup(jPanelTeam2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTeam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelTeam2Bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTeam2Actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTeam2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        jPanelTeam2Layout.setVerticalGroup(
            jPanelTeam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTeam2Layout.createSequentialGroup()
                .addGroup(jPanelTeam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTeam2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeam2Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTeam2Actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        jButtonCloseButton.setText("Close");
        jButtonCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTeam2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCloseButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTeam2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCloseButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?");
        
        //ToDo: Assign all blank fields to 0
        //ToDo: Add checks to disable Blind Nello
        //ToD0: Add checks to disable Nello
        
        if (pattern.matcher(jTextFieldTeam1Player1Bid.getText()).matches()) {
            if (pattern.matcher(jTextFieldTeam1Player2Bid.getText()).matches()) {
                if (pattern.matcher(jTextFieldTeam1Total.getText()).matches()) {
                    float num1 = Float.parseFloat(jTextFieldTeam1Player1Bid.getText());
                    float num2 = Float.parseFloat(jTextFieldTeam1Player2Bid.getText());
                    float total = Float.parseFloat(jTextFieldTeam1Total.getText());
                    float result = num1 + num2;
                    
                    float points = 0;
                    if (total >= result) {
                        points = result * 10 + (total - result);
                    }
                    else {
                        points = result * -10; 
                    }
                    
                    points += team1Nello;
                    
                    float currentScore = Float.parseFloat(jTextFieldTeam1Score.getText());
                    float newScore = currentScore + points;
                    jTextFieldTeam1Score.setText(String.valueOf(newScore));
                    
                    jTextFieldTeam1Player1Bid.setText("0");
                    jTextFieldTeam1Player2Bid.setText("0");
                    jTextFieldTeam1Total.setText("0");
                    jRadioButton5.setSelected(true);
                    team1Nello = 0;
                }
                else {
                    JOptionPane.showMessageDialog(null, jTextFieldTeam1Total.getText() + " is not a valid number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                JOptionPane.showMessageDialog(null, jTextFieldTeam1Player2Bid.getText() + " is not a valid number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
             JOptionPane.showMessageDialog(null, jTextFieldTeam1Player1Bid.getText() + " is not a valid number.", "Invalid Entry", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonTeam1NelloSucceededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTeam1NelloSucceededActionPerformed
        team1Nello = 100;
    }//GEN-LAST:event_jRadioButtonTeam1NelloSucceededActionPerformed

    private void jRadioButtonTeam1NelloFailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTeam1NelloFailedActionPerformed
        team1Nello = -100;
    }//GEN-LAST:event_jRadioButtonTeam1NelloFailedActionPerformed

    private void jRadioButtonTeam1BlindSucceededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTeam1BlindSucceededActionPerformed
        team1Nello = 200;
    }//GEN-LAST:event_jRadioButtonTeam1BlindSucceededActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        team1Nello = -200;
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        team1Nello = 0;
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpadesScoreKeeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpadesScoreKeeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpadesScoreKeeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpadesScoreKeeperUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpadesScoreKeeperUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTeam1Results;
    private javax.swing.ButtonGroup buttonGroupTeam2Results;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCloseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelTeam1;
    private javax.swing.JPanel jPanelTeam1Actual;
    private javax.swing.JPanel jPanelTeam1Bid;
    private javax.swing.JPanel jPanelTeam2;
    private javax.swing.JPanel jPanelTeam2Actual;
    private javax.swing.JPanel jPanelTeam2Bid;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButtonTeam1BlindSucceeded;
    private javax.swing.JRadioButton jRadioButtonTeam1NelloFailed;
    private javax.swing.JRadioButton jRadioButtonTeam1NelloSucceeded;
    private javax.swing.JRadioButton jRadioButtonTeam2BlindFailed;
    private javax.swing.JRadioButton jRadioButtonTeam2BlindSucceeded;
    private javax.swing.JRadioButton jRadioButtonTeam2NelloFailed;
    private javax.swing.JRadioButton jRadioButtonTeam2NelloSucceeded;
    private javax.swing.JRadioButton jRadioButtonTeam2ResultsNone;
    private javax.swing.JTextField jTextFieldTeam1Player1Bid;
    private javax.swing.JTextField jTextFieldTeam1Player2Bid;
    private javax.swing.JTextField jTextFieldTeam1Score;
    private javax.swing.JTextField jTextFieldTeam1Total;
    private javax.swing.JTextField jTextFieldTeam2Player1Bid;
    private javax.swing.JTextField jTextFieldTeam2Player2Bid;
    private javax.swing.JTextField jTextFieldTeam2Score;
    private javax.swing.JTextField jTextFieldTeam2Total;
    // End of variables declaration//GEN-END:variables
}
